DROP TABLE test1;

CREATE TABLE "user" (
id SERIAL NOT NULL PRIMARY KEY,
username VARCHAR NOT NULL UNIQUE,
first_name VARCHAR NOT NULL,
last_name VARCHAR NOT NULL,
password VARCHAR NOT NULL,
role VARCHAR NOT NULL
);



